stages:          
  - build

build-job:       
  stage: build
  image: maven:latest
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
  only:
    - develop/login-authentication


